# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  
Layout/LineLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 103
